version: 2
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 25
        javascript:
          mass_threshold: 170
  eslint:
    enabled: true
    config:
      extensions:
      - .js
      - .jsx
  fixme:
    enabled: true
    exclude_patterns:
    - "app/javascript/enums/NumberSuffixes.js"
  rubocop:
    enabled: true
    channel: rubocop-0-48
exclude_patterns:
- bin/
- config/
- db/
- docker/
- karma.conf.js
- legal/
- lib/tasks/
- log/
- node_modules/
- public/
- spec/
- vendor/